import os
from dotenv import load_dotenv
from gemini import analyze_support_request, analyze_support_summary


load_dotenv()

from slack_bolt import App

app = App(
    token=os.getenv("SLACK_BOT_TOKEN"),
    signing_secret=os.getenv("SLACK_SIGNING_SECRET"),
)


def clean_for_slack(text: str, max_length: int = 2800) -> str:
    text = text.strip()

    if len(text) > max_length:
        return text[:max_length] + "..."

    return text


@app.command("/support-summary")
def support_summary(ack, respond, command):
    ack()

    tickets = command.get("text", "").strip()

    if not tickets:
        tickets = """
        1. Student cannot connect laptop to campus Wi-Fi.
        2. Professor's classroom projector is not displaying.
        3. Staff member forgot their password and cannot log in.
        4. User reports slow computer performance after startup.
        5. Student cannot access Canvas on their phone.
        """

    try:
        summary = analyze_support_summary(tickets)
        summary = clean_for_slack(summary)

        respond(f"*SupportOps AI Daily Summary*\n\n{summary}")

    except Exception as e:
        respond(f"Sorry, I couldn’t generate the support summary. Error: `{str(e)}`")


@app.command("/support")
def handle_support_command(ack, respond, command):
    ack()

    user_text = command.get("text", "").strip()

    if not user_text:
        respond(
            response_type="ephemeral",
            text="Please include a support request. Example: `/support customer cannot log in`",
        )
        return

    analysis = clean_for_slack(analyze_support_request(user_text))

    respond(
        response_type="in_channel",
        text="SupportOps AI Triage",
        blocks=[
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "SupportOps AI Triage",
                    "emoji": True,
                },
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Original request:*\n>{user_text}",
                },
            },
            {
                "type": "divider",
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": analysis,
                },
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "Generated by *SupportOps AI* to help teams triage support requests faster.",
                    }
                ],
            },
        ],
    )


if __name__ == "__main__":
    port = int(os.getenv("PORT", 3000))
    app.start(port=port)